# Generated by Django 5.0.6 on 2024-07-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_user_favoritelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favoriteList',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='myapp.stock'),
        ),
    ]
