# Generated by Django 5.0.6 on 2024-07-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_stock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
