# Generated by Django 5.0.6 on 2024-07-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_stock_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='market',
        ),
    ]
