# Generated by Django 5.0.6 on 2024-07-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_stock_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
