# Generated by Django 5.0.6 on 2024-07-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_user_favoritelist_delete_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favoriteList',
            field=models.JSONField(),
        ),
    ]
