# Generated by Django 5.0.6 on 2024-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_user_favoritelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favoriteList',
            field=models.CharField(max_length=5000),
        ),
    ]
