# Generated by Django 5.0.6 on 2024-07-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_favoritelist_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='strategyList',
            field=models.JSONField(default=str, verbose_name='json'),
        ),
    ]
